import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Cart",
  description: "Generated by Mahmoud Gamal",
};

function page() {
  return <div>Cart</div>;
}

export default page;
