import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by Mahmoud Gamal",
  icons: {
    icon: "./images/login.svg",
  },
};

export default function SignInLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <section>{children}</section>;
}
