import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login",
  description: "Generated by Mahmoud Gamal",
  icons: {
    icon: "./images/login.svg",
  },
};
function SignINPage() {
  return <div>SignINPage page</div>;
}

export default SignINPage;
