import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by Mahmoud Gamal",
  icons: {
    icon: "./images/register.svg",
  },
};

export default function RegisterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
