import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Register",
  description: "Generated by Mahmoud Gamal",
  icons: {
    icon: "./images/register.svg",
  },
};
function page() {
  return <div>Register</div>;
}

export default page;
